unit MsgDialogs;

{Auto-generated by Dam - 30/01/2019 11:25:05}

interface

uses DamUnit;

procedure MsgInfo(const Msg: String; const Params: TDamParams = nil);
procedure MsgWarn(const Msg: String; const Params: TDamParams = nil);
procedure MsgError(const Msg: String; const Params: TDamParams = nil);
function MsgQuest(const Msg: String; const Params: TDamParams = nil): Boolean;
procedure MsgRaise(const Msg: String; const Params: TDamParams = nil);
function CaptureErrorMsg: String;
procedure ShowErrorMsg;

procedure InfoGoodJob;
function QuestionSaveFile(Params: TDamParams): Boolean;
procedure RaiseLoadingFile(Params: TDamParams);

implementation

uses UFrmExample;

procedure MsgInfo(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgInfo(Msg, Params);
end;

procedure MsgWarn(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgWarn(Msg, Params);
end;

procedure MsgError(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgError(Msg, Params);
end;

function MsgQuest(const Msg: String; const Params: TDamParams): Boolean;
begin
  Result := DamUnit.MsgQuest(Msg, Params);
end;

procedure MsgRaise(const Msg: String; const Params: TDamParams);
begin
  DamUnit.MsgRaise(Msg, Params);
end;

function CaptureErrorMsg: String;
begin
  Result := DamUnit.CaptureErrorMsg;
end;

procedure ShowErrorMsg;
begin
  DamUnit.ShowErrorMsg;
end;

//-- Messages methods of TDamMsg objects

procedure InfoGoodJob;
begin
  FrmExample._InfoGoodJob.Run;
end;

function QuestionSaveFile(Params: TDamParams): Boolean;
begin
  Result := FrmExample._QuestionSaveFile.RunAsBool(Params);
end;

procedure RaiseLoadingFile(Params: TDamParams);
begin
  FrmExample._RaiseLoadingFile.Run(Params);
end;

end.
