unit MsgDialogs;

{Auto-generated by Dam - 15/11/2020 15:14:10}

interface

uses DamUnit;

function DamParams(const Params: array of Variant): TDamParams;

procedure MsgInfo(const Msg: string; const Params: TDamParams = nil);
procedure MsgWarn(const Msg: string; const Params: TDamParams = nil);
procedure MsgError(const Msg: string; const Params: TDamParams = nil);
function MsgQuest(const Msg: string; const Params: TDamParams = nil): Boolean;
procedure MsgRaise(const Msg: string; const Params: TDamParams = nil);
function CaptureErrorMsg: string;
procedure ShowErrorMsg;

procedure InfoGoodJob;
function QuestionSaveFile(Params: TDamParams): Boolean;
procedure RaiseLoadingFile(Params: TDamParams);

implementation

uses UFrmExample;

function DamParams(const Params: array of Variant): TDamParams;
begin
  Result := DamUnit.DamParams(Params);
end;

procedure MsgInfo(const Msg: string; const Params: TDamParams);
begin
  DamUnit.MsgInfo(Msg, Params);
end;

procedure MsgWarn(const Msg: string; const Params: TDamParams);
begin
  DamUnit.MsgWarn(Msg, Params);
end;

procedure MsgError(const Msg: string; const Params: TDamParams);
begin
  DamUnit.MsgError(Msg, Params);
end;

function MsgQuest(const Msg: string; const Params: TDamParams): Boolean;
begin
  Result := DamUnit.MsgQuest(Msg, Params);
end;

procedure MsgRaise(const Msg: string; const Params: TDamParams);
begin
  DamUnit.MsgRaise(Msg, Params);
end;

function CaptureErrorMsg: string;
begin
  Result := DamUnit.CaptureErrorMsg;
end;

procedure ShowErrorMsg;
begin
  DamUnit.ShowErrorMsg;
end;

//-- Messages methods of TDamMsg objects

procedure InfoGoodJob;
begin
  FrmExample._InfoGoodJob.Run;
end;

function QuestionSaveFile(Params: TDamParams): Boolean;
begin
  Result := FrmExample._QuestionSaveFile.RunAsBool(Params);
end;

procedure RaiseLoadingFile(Params: TDamParams);
begin
  FrmExample._RaiseLoadingFile.Run(Params);
end;

end.
